SCALE_FACTOR = 2
TILE_WIDTH   = 16 
TILE_HEIGHT  = 16
WORLD_WIDTH  = 40
WORLD_HEIGHT = 30

WINDOW_WIDTH  = WORLD_WIDTH * TILE_WIDTH * SCALE_FACTOR
WINDOW_HEIGHT = WORLD_HEIGHT * TILE_HEIGHT * SCALE_FACTOR