SCALE_FACTOR = 4
TILE_WIDTH   = 16 
TILE_HEIGHT  = 16
WORLD_WIDTH  = 20
WORLD_HEIGHT = 15

PIXEL_WIDTH = WORLD_WIDTH * TILE_WIDTH
PIXEL_HEIGHT = WORLD_HEIGHT * TILE_HEIGHT

HUD_HEIGHT = 32

SCREEN_WIDTH  = PIXEL_WIDTH  * SCALE_FACTOR
SCREEN_HEIGHT = PIXEL_HEIGHT * SCALE_FACTOR

WINDOW_WIDTH  = SCREEN_WIDTH
WINDOW_HEIGHT = SCREEN_HEIGHT + HUD_HEIGHT